# Generated by Django 2.0 on 2018-01-13 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(default='No description.')),
                ('location', models.CharField(max_length=300)),
                ('image', models.FileField(default='generic/img/series-placeholder.png', upload_to='')),
                ('returned', models.BooleanField(default=False)),
                ('lost_found', models.CharField(default='found', max_length=5)),
                ('added_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
