# Generated by Django 2.0 on 2018-01-13 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jacket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jacket',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jacket',
            name='description',
            field=models.TextField(),
        ),
    ]
